server:
    port: 8080
    context-path: #/ruyue/
    cache:
        type: redis
logging:
    level:
        tk.mybatis: DEBUG
        com.ry.taxi: DEBUG   
    config: classpath:logback-spring.xml   

spring:
    datasource:
        name: ruyue
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 100
        initialSize: 1
        maxWait: 60000
        minIdle: 10
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
    http:
       encoding:
            charset: utf-8
            enabled: true
            force: true
       content-type: text/html 
       timeout:
            connect: 60000
            read: 60000
            write: 60000
       headers:
            Connection: close
       dispatcher: 
          maxRequests: 500
          maxRequestsPerHost: 50    
    thread:
        corePoolSize: 15
        maxPoolSize: 100
        queueSize: 5000
