spring:
  datasource:
    url: jdbc:mysql://szycwh.f3322.net:3306/carservicedev_v4.0.0?useUnicode=true&characterEncoding=utf-8
    username: xxdeveloper
    password: xxkj@2017
  rabbitmq:
    host: szycwh.f3322.net
    port: 5672
    username: whzj01
    password: 123456
    virtual-host: APPServer
    queue-default-name: supervision_api_object_queue
    queue-default-validtime:  300000
service:
  url: http://120.76.199.119:8099/api/transfer
  #地图坐标类型
  map-encrypt:  3
  company:
    code: RY
    key: SLj16Qq7FK9nbyi4
    open-token: dsjjaAGJDJ224JD
server:
  port: 8098
carservice-api: http://localhost:8080/carservice-api/api
